name: 02 - Workflow Events
on: 
  push:
  workflow_dispatch:
  pull_request:
  schedule: 
    - cron: "5 * 28 9 *"
jobs:
   echo:
    runs-on: ubuntu-latest
    steps:
     - name: Show the trigger
       run: echo "Name of the event ${{github.event_name}}"
  
  
    
       
